
const flags = {
  INCIDENT: 'INCIDENT',
  ANNOUNCEMENT: 'ANNOUNCEMENT',
  ADMIN: 'ADMIN',
  ANNOUNCEMENT_TYPE: 'ANNOUNCEMENT_TYPE',
  CHECKLIST_DAILY: 'CHECKLIST_DAILY',
  CHECKLIST: 'CHECKLIST',
  CONFIG: 'CONFIG',
  INCIDENT_DAMAGE: 'INCIDENT_DAMAGE',
  INCIDENT_SEVERITY: 'INCIDENT_SEVERITY',
  INCIDENT_TYPE: 'INCIDENT_TYPE',
  JOB_SITE: 'JOB_SITE',
  JOB_TYPE: 'JOB_TYPE',
  JOB: 'JOB',
  ROLE: 'ROLE',
  DASHBOARD: 'DASHBOARD',
}

export default flags;